import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateProjectReport = (projects) => {
  // Create new PDF document
  const pdf = new jsPDF();
  
  // Add title
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Project Management Report', 20, 20);
  
  // Add generation date
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  const currentDate = new Date().toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric'
  });
  pdf.text(`Generated on: ${currentDate}`, 20, 30);
  
  // Add total projects count
  pdf.text(`Total Projects: ${projects.length}`, 20, 40);
  
  // Prepare table data
  const tableData = projects.map(project => {
    console.log('Processing project:', project);
    return [
      project.name || 'N/A',
      project.client || 'N/A',
      project.status || 'N/A',
      project.startDate ? new Date(project.startDate).toLocaleDateString('en-GB') : 'N/A',
      project.endDate ? new Date(project.endDate).toLocaleDateString('en-GB') : 'N/A',
      project.budget ? `Rs. ${Number(project.budget).toLocaleString()}` : 'N/A',
      `${Number(project.completion) || 0}%`
    ];
  });
  
  // Define table columns
  const columns = [
    'Project Name',
    'Client',
    'Status',
    'Start Date',
    'End Date',
    'Budget',
    'Completion %'
  ];
  
  // Add table to PDF
  autoTable(pdf, {
    head: [columns],
    body: tableData,
    startY: 50,
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [59, 130, 246], // Blue color
      textColor: 255,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252], // Light gray
    },
    columnStyles: {
      0: { cellWidth: 30 }, // Project Name
      1: { cellWidth: 25 }, // Client
      2: { cellWidth: 20 }, // Status
      3: { cellWidth: 20 }, // Start Date
      4: { cellWidth: 20 }, // End Date
      5: { cellWidth: 25 }, // Budget
      6: { cellWidth: 20 }, // Completion
    },
    margin: { left: 20, right: 20 },
  });
  
  // Add summary statistics
  const finalY = 200; // Approximate position after table
  
  // Calculate statistics
  const completedProjects = projects.filter(p => p.status === 'Completed').length;
  const inProgressProjects = projects.filter(p => p.status === 'In Progress').length;
  const planningProjects = projects.filter(p => p.status === 'Planning').length;
  const onHoldProjects = projects.filter(p => p.status === 'On Hold').length;
  
  const totalBudget = projects.reduce((sum, p) => sum + (Number(p.budget) || 0), 0);
  const averageCompletion = projects.length > 0 
    ? (projects.reduce((sum, p) => sum + (Number(p.completion) || 0), 0) / projects.length).toFixed(1)
    : 0;
  
  // Add summary section
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Project Summary', 20, finalY);
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`• Completed Projects: ${completedProjects}`, 20, finalY + 10);
  pdf.text(`• In Progress: ${inProgressProjects}`, 20, finalY + 20);
  pdf.text(`• Planning: ${planningProjects}`, 20, finalY + 30);
  pdf.text(`• On Hold: ${onHoldProjects}`, 20, finalY + 40);
  pdf.text(`• Total Budget: Rs. ${totalBudget.toLocaleString()}`, 20, finalY + 50);
  pdf.text(`• Average Completion: ${averageCompletion}%`, 20, finalY + 60);
  
  // Add footer
  const pageHeight = pdf.internal.pageSize.height;
  pdf.setFontSize(8);
  pdf.text('Generated by AD Construction Project Management System', 20, pageHeight - 20);
  
  return pdf;
};

export const downloadProjectReport = (projects) => {
  try {
    console.log('Starting PDF generation with projects:', projects);
    
    if (!projects || !Array.isArray(projects)) {
      console.error('Invalid projects data:', projects);
      return false;
    }
    
    const pdf = generateProjectReport(projects);
    console.log('PDF generated successfully');
    
    const fileName = `Project_Report_${new Date().toISOString().split('T')[0]}.pdf`;
    console.log('Saving PDF with filename:', fileName);
    
    pdf.save(fileName);
    console.log('PDF saved successfully');
    
    return true;
  } catch (error) {
    console.error('Error generating PDF:', error);
    console.error('Error details:', error.message);
    console.error('Error stack:', error.stack);
    return false;
  }
};

const pdfService = {
  generateProjectReport,
  downloadProjectReport,
};

export default pdfService;
