import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export function generateInventoryReportPDF({ items, stats }) {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(22);
  doc.text('Inventory Report', 14, 18);
  doc.setFontSize(12);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 26);
  doc.text('AD Construction', 150, 18, { align: 'right' });
  doc.text('Colombo, Sri Lanka', 150, 24, { align: 'right' });

  // Insights/Stats Section
  doc.setFontSize(14);
  doc.text('Inventory Insights', 14, 38);
  doc.setFontSize(12);
  let y = 44;
  doc.setTextColor(239, 68, 68 ); // green
  doc.text(`Total Items: ${stats.totalItems}`, 14, y);
  y += 7;
  doc.setTextColor(59, 130, 246); // blue
  doc.text(`Total Value: Rs. ${Number(stats.totalValue).toLocaleString()}`, 14, y);
  y += 7;
  doc.setTextColor(251, 191, 36); // orange
  doc.text(`Low Stock Items (< 10 units): ${stats.lowStock}`, 14, y);
  y += 7;
  doc.setTextColor(239, 68, 68); // red
  doc.text(`Out of Stock Items: ${stats.outOfStock}`, 14, y);
  y += 10;
  doc.setTextColor(0,0,0);

  // Table of all items
  autoTable(doc, {
    head: [[
      'Name', 'Type', 'Seller', 'Qty', 'Unit', 'Unit Price', 'Total Value', 'Status'
    ]],
    body: items.map(item => [
      item.name,
      item.type,
      item.seller,
      item.amount,
      item.metric || 'Units',
      `Rs. ${Number(item.unitPrice).toLocaleString()}`,
      `Rs. ${(item.amount * item.unitPrice).toLocaleString()}`,
      item.amount === 0 ? 'out_of_stock' : item.status
    ]),
    startY: y,
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 10, cellPadding: 2 },
    alternateRowStyles: { fillColor: [243, 244, 246] },
    margin: { left: 14, right: 14 },
  });

  const finalY = doc.lastAutoTable?.finalY || y + 20;
  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128);
  doc.text('Report generated by AD Construction Inventory System', 14, finalY + 10);

  doc.save('Inventory_Report.pdf');
}
